### ISSUE TITLE
Results need to be sortable/pageable and handle large amount of data

### ISSUE THREAD

**Issue by jamescummings** [philipallfrey/teihub#2]
Currently the tabbed results are paged, but these should also be sortable by any column and filterable by content of any row. I'm thinking of dataTables type output. However, the solution will need to be server-side rather than in browser since once you get a full results list that will be unmanageable, I'm assuming.

**Comment by philipallfrey** [comment]
@jamescummings I gave this some thought when I implemented the table (Semantic UI which I am using does have a table sorter built in); but there's a couple of constraints involved.

In an ideal world, or with a smaller dataset, it would be easy to render the full table of results, and have it sortable/filterable with javascript in the browser. But looking ahead to the full ~2M result set of teiheader matches from GitHub, that approach won't work. My estimate is that a JSON file with the results would be around 10–15MB; the rendered HTML would be similar. Trying to sort/filter that in the browser would be painfully slow, as you suggest, though perhaps it would be worth trying it to see.

While I do use a database (FaunaDB) to store the results, I don't really want to do server-side sorting/filtering for three reasons. One, this is a side project and that adds an extra layer of complexity. Two, it gives me a chance to test out using a static site generator. Three, the free database tier only gives 100K reads per day, and while I don't expect the site to get too much traffic, for maximum sustainability I don't want to assume that this limit won't be reached.

What I chose instead was to do the sorting/pagination at build time (i.e. with every new set of results), and generate a set of tables sorted by date, repo name, and matches. If the results are being paginated anyway my feeling was that there was little difference to the end user whether they are viewing a static page, or one generated by a server-side database query.

I could easily create the illusion of the columns being sortable by removing the current tabs, and moving the links to the different views to the column headers; that might actually be better UX. It will still reload the whole page, though.

I didn't think there would be a use case for sorting by the repo description, though I can see that repos with a description are often more interesting/correspond to a more fully developed project. It's easy enough to add this in, so I will do that.

I also didn't considering filtering by row content. Can you give a use case? Repo name is unique, so there's no point filtering on that. Description is almost unique, except for empty descriptions, and forks/copies of repos, so again I didn't see the point.

**Comment by philipallfrey** [comment]
Closing this, as columns are now sortable by clicking on the header. This is a better interface than my first concept (and because the pages are static HTML, the full page reload is fast) so thanks for the suggestion.

I will tweak the description sorting to put the empty descriptions at the end.
